import type { MenuData } from "./menu-types";

/**
 * Initial menu, written to `data/menu.json` on first run. Once that file
 * exists it is the source of truth and this seed is no longer read.
 */
export const seedMenu: MenuData = {
  settings: {
    phone: "42 25 39 09 / 098 253 909",
    whatsapp: "59898253909",
    email: "contacto@parrilladalabalanza.com.uy",
    hours: [
      { days: "Martes a viernes", time: "11:30 – 23:30" },
      { days: "Sábados y domingos", time: "11:30 – 24:00" },
      { days: "Lunes", time: "Cerrado" },
    ],
    specialClosings: [],
  },
  categories: [
    { id: "cat-parrilla", name: "Parrilla", published: true, order: 1 },
    { id: "cat-minutas", name: "Minutas", published: true, order: 2 },
    { id: "cat-pastas", name: "Pastas caseras", published: true, order: 3 },
    { id: "cat-guarniciones", name: "Guarniciones", published: true, order: 4 },
    { id: "cat-postres", name: "Postres", published: true, order: 5 },
  ],
  items: [
    {
      id: "item-asado-tira",
      name: "Asado de tira",
      description:
        "500 grs. aprox. de asado tierno al fuego de leña, con guarnición.",
      price: 790,
      categoryId: "cat-parrilla",
      featured: true,
      published: true,
      order: 1,
    },
    {
      id: "item-entrana",
      name: "Entraña",
      description: "Corte seleccionado a las brasas, jugoso, con guarnición.",
      price: 890,
      categoryId: "cat-parrilla",
      featured: true,
      published: true,
      order: 2,
    },
    {
      id: "item-vacio",
      name: "Vacío",
      description: "Clásico de la parrilla, cocción lenta. Con guarnición.",
      price: 760,
      categoryId: "cat-parrilla",
      featured: false,
      published: true,
      order: 3,
    },
    {
      id: "item-pollo",
      name: "Medio pollo a la parrilla",
      description: "Marinado de la casa, dorado al fuego. Con guarnición.",
      price: 620,
      categoryId: "cat-parrilla",
      featured: false,
      published: true,
      order: 4,
    },
    {
      id: "item-chivito",
      name: "Chivito al plato",
      description:
        "Lomo, jamón, queso, panceta, huevo, con papas fritas y ensalada rusa.",
      price: 850,
      categoryId: "cat-minutas",
      featured: true,
      published: true,
      order: 5,
    },
    {
      id: "item-milanesa",
      name: "Milanesa napolitana con papas fritas",
      description: "Milanesa de carne con salsa, jamón y muzzarella gratinada.",
      price: 690,
      categoryId: "cat-minutas",
      featured: false,
      published: true,
      order: 6,
    },
    {
      id: "item-sorrentinos",
      name: "Sorrentinos de jamón y queso",
      description: "Caseros, con salsa a elección: fileto, crema o bolognesa.",
      price: 480,
      categoryId: "cat-pastas",
      featured: true,
      published: true,
      order: 7,
    },
    {
      id: "item-canelones",
      name: "Canelones de verdura y ricota",
      description: "Masa casera, gratinados al horno. Opción vegetariana.",
      price: 440,
      categoryId: "cat-pastas",
      featured: false,
      published: true,
      order: 8,
    },
    {
      id: "item-ravioles",
      name: "Ravioles de la casa",
      description: "Con salsa a elección. Consultá por la opción sin TACC.",
      price: 420,
      categoryId: "cat-pastas",
      featured: false,
      published: true,
      order: 9,
    },
    {
      id: "item-papas",
      name: "Papas fritas",
      description: "Porción abundante, recién hechas.",
      price: 260,
      categoryId: "cat-guarniciones",
      featured: false,
      published: true,
      order: 10,
    },
    {
      id: "item-ensalada",
      name: "Ensalada de la casa",
      description: "Verdes de estación, tomate, palmitos y huevo.",
      price: 320,
      categoryId: "cat-guarniciones",
      featured: false,
      published: true,
      order: 11,
    },
    {
      id: "item-boniato",
      name: "Boniato glaseado",
      description: "Al horno, con un toque de azúcar rubia.",
      price: 240,
      categoryId: "cat-guarniciones",
      featured: false,
      published: true,
      order: 12,
    },
    {
      id: "item-flan",
      name: "Flan casero con dulce de leche",
      description: "Receta de siempre, con abundante dulce de leche.",
      price: 220,
      categoryId: "cat-postres",
      featured: true,
      published: true,
      order: 13,
    },
    {
      id: "item-panqueque",
      name: "Panqueque de dulce de leche",
      description: "Tibio, con azúcar quemada.",
      price: 230,
      categoryId: "cat-postres",
      featured: false,
      published: true,
      order: 14,
    },
  ],
};
